# Generated by Django 6.1.1 on 2026-09-13 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeComunicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.CharField(blank=True, max_length=50, unique=True)),
                ('asunto', models.CharField(max_length=150)),
                ('cuerpo_mensaje', models.TextField()),
                ('tipo_comunicacion', models.CharField(choices=[('general', 'Comunicado general'), ('citacion', 'Citación / Reunión'), ('academico', 'Aviso académico'), ('disciplinario', 'Aviso disciplinario'), ('respuesta', 'Respuesta directa')], default='general', max_length=40)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='comunicados/')),
                ('copia_utp_direccion', models.BooleanField(default=False, verbose_name='Copia a UTP/Dirección')),
                ('requiere_firma_digital', models.BooleanField(default=False)),
                ('exige_recibo_lectura', models.BooleanField(default=False)),
                ('fecha_hora_envio', models.DateTimeField(auto_now_add=True)),
                ('leido', models.BooleanField(default=False)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('curso_destino', models.ForeignKey(blank=True, help_text='Usar para comunicar a todos los apoderados de un curso.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='academico.curso')),
            ],
            options={
                'verbose_name': 'Mensaje / Comunicado',
                'verbose_name_plural': 'Mensajes / Comunicados',
                'ordering': ['-fecha_hora_envio'],
            },
        ),
    ]
