# Generated by Django 6.1.1 on 2026-09-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('porcentaje_asistencia_actual', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('atraso', 'Atraso'), ('justificado', 'Justificado')], default='presente', max_length=20)),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grado_curso', models.CharField(max_length=50, verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['grado_curso'],
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_estudiante', models.CharField(max_length=12, unique=True, verbose_name='RUT del estudiante')),
                ('nombre_completo', models.CharField(max_length=150)),
                ('apellido_familiar', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'ordering': ['nombre_completo'],
            },
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('clase', 'Clase'), ('evaluacion', 'Evaluación'), ('reunion', 'Reunión'), ('otro', 'Otro')], default='clase', max_length=20)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='JustificacionRetiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_solicitud', models.CharField(choices=[('retiro_anticipado', 'Retiro anticipado'), ('inasistencia', 'Justificación de inasistencia'), ('atraso', 'Justificación de atraso')], max_length=30)),
                ('motivo_texto', models.TextField()),
                ('archivo_certificado', models.FileField(blank=True, null=True, upload_to='justificaciones/')),
                ('estado_aprobacion', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Justificación de retiro',
                'verbose_name_plural': 'Justificaciones de retiro',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Observacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('positiva', 'Positiva'), ('negativa', 'Negativa'), ('academica', 'Académica'), ('otra', 'Otra')], default='otra', max_length=30)),
                ('contenido_texto', models.TextField()),
                ('confidencial', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Observación',
                'verbose_name_plural': 'Observaciones',
                'ordering': ['-fecha'],
            },
        ),
    ]
