# Generated by Django 6.1.1 on 2026-09-13 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='curso',
            name='docente_jefe',
            field=models.ForeignKey(blank=True, limit_choices_to={'rol': 'docente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='apoderado',
            field=models.ForeignKey(limit_choices_to={'rol': 'apoderado'}, on_delete=django.db.models.deletion.CASCADE, related_name='estudiantes_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiantes', to='academico.curso'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academico.estudiante'),
        ),
        migrations.AddField(
            model_name='evento',
            name='creado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evento',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='academico.curso'),
        ),
        migrations.AddField(
            model_name='justificacionretiro',
            name='apoderado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_enviadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='justificacionretiro',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='academico.estudiante'),
        ),
        migrations.AddField(
            model_name='observacion',
            name='docente_o_inspector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='observacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones', to='academico.estudiante'),
        ),
    ]
