# Generated by Django 6.1.1 on 2026-09-18 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservacionComportamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=200)),
                ('tipo_observacion', models.CharField(choices=[('NEGATIVA', 'Negativa'), ('POSITIVA', 'Positiva'), ('ESPECIALISTA', 'Requiere especialista')], max_length=20)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('NO_VISTA', 'No vista'), ('EN_PROCESO', 'En proceso'), ('RESUELTA', 'Resuelta')], default='NO_VISTA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('resolucion', models.TextField(blank=True, null=True)),
                ('administrativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observaciones_modificadas', to=settings.AUTH_USER_MODEL)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.curso')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observaciones_comportamiento_creadas', to=settings.AUTH_USER_MODEL)),
                ('estudiantes', models.ManyToManyField(to='academico.estudiante')),
            ],
        ),
    ]
